const translations = {
    en: {
        Accueuil: "Home",
        A_propos: "About",
        Services_loisirs: "Services & Leisure",
        Action: "Action",
        Another_action: "Another action",
        Service_action: "Service action",
        Another_service_action: "Another service action",
        Something_else_here: "Something else here",
        Tarifs: "Rates",
        Contact: "Contact",
        header_title: "Enjoy your dream vacation",
        header_desc: "Book your stay now and enjoy the best offers and exclusive rates.",
        checkin_date: "Add check-in date",
        checkout_date: "Add check-out date",
        choose_room_type: "Choose room type",
        single_room: "Single Room",
        double_room: "Double Room",
        junior_suite_single: "Junior Suite Single",
        junior_suite_double: "Junior Suite Double",
        senior_suite_single: "Senior Suite Single",
        senior_suite_double: "Senior Suite Double",
        our_services: "Our Services",
        room: "Room",
        meeting_room: "Meeting Room",
        restaurant: "Restaurant",
        book_now: "Book Now",
        client_testimonials: "What Our Clients Say",
        client_feedback_1: "The hotel is very clean and quiet, the reception was good, the rooms are spacious and comfortable, the bed is very pleasant, you can stay all day. The WiFi is excellent, the breakfast was very delicious and varied. I fully recommend this charming hotel.",
        client_feedback_2: "I had an excellent experience, great service, an amazing hotel, happy to see such customer service in BBA, thanks to the Hotel Beni Hamad team, one day I will come back. Some small things need improvement but overall, it was fantastic.",
        client_feedback_3: "I highly recommend the hotel which is pleasant, quiet, clean, and the team is very professional and above all competent. A big thank you to Foued at the reception who is really the first contact that makes all the difference, followed by very pleasant service in the restaurant by Abdel, which made the stay pleasant and worth repeating. Best regards.",
        discount_codes: "Discount Codes",
        join_rewards: "Join the rewards and discover incredible discounts on your purchases at Beni Hamad",
        join_rewards_btn: "Join the rewards",
        footer_desc_1: "Beni Hamad stands out as a unique destination to stay, embodying the beauty of simplicity and comfort in one exceptional hotel. With its distinctive character and unique services.",
        footer_desc_2: "Beni Hamad offers travelers the opportunity to explore the region in complete tranquility and ease.",
        contact: "Contact",
        email: "info@hotel-benihamad.dz",
        phone: "+213(0)35.69.02.02",
        meeting_room: "Luxury Meeting Room",
        meeting_room_description: "The BENI-HAMAD hotel has a meeting room for 45 people. Our staff's experience and expertise guarantee the success of your event.",
        date_label: "Date:",
        time_label: "Time:",
        duration_label: "Duration:",
        name_label: "Name:",
        email_label: "Email:",
        reserve_button: "Reserve the Room",
    },
    fr: {
        Accueuil: "Accueuil",
        A_propos: "A propos",
        Services_loisirs: "Services & loisirs",
        Action: "Action",
        Another_action: "Autre action",
        Service_action: "Action de service",
        Another_service_action: "Autre action de service",
        Something_else_here: "Quelque chose d'autre ici",
        Tarifs: "Tarifs",
        Contact: "Contact",
        header_title: "Profitez de votre vocation de rêve",
        header_desc: "Réservez votre séjour dès maintenant et profitez des meilleures offres et des tarifs exclusifs.",
        checkin_date: "Ajouter la Date d'arrivée",
        checkout_date: "Ajouter date de départ",
        choose_room_type: "Choisissez le type de chambre",
        single_room: "Chambre single",
        double_room: "Chambre double",
        junior_suite_single: "Suite Junior single",
        junior_suite_double: "Suite Junior double",
        senior_suite_single: "Suite Senior single",
        senior_suite_double: "Suite Senior double",
        our_services: "Nos services",
        room: "Chambre",
        meeting_room: "Salle de réunion",
        restaurant: "Restaurant",
        book_now: "Réserver maintenant",
        client_testimonials: "Ce que disent nos clients",
        client_feedback_1: "L'hôtel est très propre et calme, l'accueil était bon, les chambres sont spacieuses et confortables, le lit est très agréable, on peut y rester toute la journée. Le WiFi est excellent, le petit-déjeuner était très délicieux et varié. Je recommande pleinement cet hôtel charmant.",
        client_feedback_2: "J'ai eu une excellente expérience, un service formidable, un hôtel incroyable, heureux de voir un tel service client à BBA, merci à l'équipe de l'Hôtel Beni Hamad, un jour je reviendrai. Il faut améliorer de petites choses mais dans l'ensemble, c'était fantastique.",
        client_feedback_3: "Je recommande vivement l'hôtel qui est agréable, calme, propre et l'équipe est très professionnelle et surtout compétente. Un grand merci à Foued à la réception qui est vraiment le premier contact qui fait toute la différence, suivi d'un service très agréable au restaurant par Abdel, ce qui a rendu le séjour plaisant et digne d'être répété. Cordialement.",
        discount_codes: "Codes de réduction",
        join_rewards: "Rejoignez les récompenses et découvrez des remises incroyables sur vos achats à Beni Hamad",
        join_rewards_btn: "Rejoignez les récompenses",
        footer_desc_1: "Beni Hamad se distingue en tant que destination unique pour séjourner, incarnant la beauté de la simplicité et du confort dans un seul hôtel exceptionnel. Grâce à son caractère distinctif et à ses services uniques.",
        footer_desc_2: "Beni Hamad offre aux voyageurs l'opportunité d'explorer la région en toute tranquillité et facilité.",
        contact: "Contact",
        email: "info@hotel-benihamad.dz",
        phone: "+213(0)35.69.02.02",
        meeting_room: "Salle de réunion de luxe",
        meeting_room_description: "L’hôtel BENI-HAMAD possède une salle de réunion pour 45 places. L’expérience et le savoir-faire de notre personnel garantissent la réussite de votre événement.",
        date_label: "Date :",
        time_label: "Heure :",
        duration_label: "Durée :",
        name_label: "Nom :",
        email_label: "Email :",
        reserve_button: "Réserver la salle",
        
    }
};

const languageSelector = document.querySelector("select");
languageSelector.addEventListener("change", (event) => {
    setLanguage(event.target.value);
});

const setLanguage = (language) => {
    const elements = document.querySelectorAll("[data-i18n]");
    elements.forEach((element) => {
        const translationKey = element.getAttribute("data-i18n");
        element.textContent = translations[language][translationKey];
    });
};
